# =================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: localhost #change to your hostname if running your own instance
        port: 5000
    url: https://sb19.linked-data.internetofwater.dev #change to host URL  if running your own instance
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    language: en-US
    cors: true
    gzip: true
    pretty_print: true
    limit: 100
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '<a href="https://www.openstreetmap.org/copyright">Â© OpenStreetMap contributors</a>'
    ogc_schemas_location: /opt/schemas.opengis.net
    templates:
      path: /skin-dashboard/templates
      static: /skin-dashboard/static

logging:
    level: ERROR
    logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: California Stream Gage Assessment
        description: Provides reference features for Stream Gage assessment and Planning Tools
        keywords:
            - geospatial
            - data
            - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://github.com/internetofwater/geoconnex.us
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Team geoconnex
        url: https://github.com/internetofwater/geoconnex.us
    contact:
        address: 2111 Campus Dr
        city: Durham
        stateorprovince: North Carolina
        postalcode: 27708
        country: USA
        email: kyle.onda@duke.edu
        url: https://internetofwater.org
        role: pointOfContact

resources:
    ca_gages:
        type: collection
        title: Gages
        description: Streamgage catalog for CA SB19
        geojsonld: False
        keywords:
            - Streamgages
        context:
            - schema: https://schema.org/
              sitename: schema:name
#             weblink: 
#                 "@id": schema:subjectOf
#                 "@type": "@id"
              weblink: 
                  "@id": "schema:about"
                  "@type": "@id"
              comid:
                  "@id": "http://www.opengeospatial.org/standards/waterml2/hy_features/flowpath"
                  "@type": "@id"
              provider: 
                  "@id": "schema:url"
              hu08:
                  "@id": "schema:geoWithin"
                  "@type": "@id"
              hu10:
                  "@id": "schema:geoWithin"
                  "@type": "@id"
              hu12:
                  "@id": "schema:geoWithin"
                  "@type": "@id"
        links:
            - type: application/html
              rel: canonical
              title: data source
              href: https://gispublic.waterboards.ca.gov/portal/home/item.html?id=32dfb85bd2744487affe6e3475190093
              hreflang: en-US
        extents:
            spatial:
                bbox: [-124.40959,32.534,-114.13121,42.00984]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: null
                end: null
        providers:
          - type: feature
            name: SQLiteGPKG
            data: /data/ca_gages.gpkg
            id_field: siteid
            uri_field: uri
            table: ca_gages
